name: Rust

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose
